#!/bin/sh

VER=`date '+%y%m%d'`

if [ $# -ge 1 ] ; then
	VER=$1
fi

DIST="${DIST:-../dist}"

NAME=diskcart-$VER
TMPDIR="${DIST}/tmp/${NAME}"

mkdir -p "${TMPDIR}/src/cartsio"
mkdir -p "${TMPDIR}/src/libflash"
mkdir -p "${TMPDIR}/src/mypdos"
mkdir -p "${TMPDIR}/src/hisio"
mkdir -p "${TMPDIR}/src/targets"

cp -a \
	atr2cart.exe \
	diskcart.atr \
	diskcart-atarimax8.com \
	diskcart-freezer2005.com diskcart-freezer2011.com \
	diskcart-mega512.com diskcart-mega4096.com \
	diskcart-sxegs512.com \
	README.txt \
	"${TMPDIR}"

cp -a Makefile piconame*.txt *.inc *.src *.cpp *.c *.h "${TMPDIR}/src"
cp -a cartsio/*.src cartsio/*.inc "${TMPDIR}/src/cartsio"
cp -a libflash/*.src libflash/*.inc "${TMPDIR}/src/libflash"
cp -a mypdos/*.src mypdos/*.inc "${TMPDIR}/src/mypdos"
cp -a hisio/*.src hisio/*.inc "${TMPDIR}/src/hisio"
cp -a targets/*.c targets/*.inc targets/*.mk "${TMPDIR}/src/targets"

rm -f "${DIST}/${NAME}".zip
cd "${DIST}/tmp"
zip -r "../${NAME}.zip" ${NAME}
cd ..
rm -rf tmp
