#!/bin/sh

if [ $# -ne 1 ] ; then
	echo "usage: $0 version"
	exit 1;
fi

NAME=mypdos$1

mkdir -p tmp/"${NAME}"/src
mkdir -p dist
rm -f dist/${NAME}.zip
cp -a README.txt LICENSE MYPDOS.COM mypdos.atr tmp/"${NAME}"
cp -a Makefile *.src tmp/"${NAME}"/src
cd tmp
zip -r ../dist/${NAME}.zip ${NAME}
rm -rf "${NAME}"
