#!/bin/sh

VER=`date '+%y%m%d'`

if [ $# -ge 1 ] ; then
	VER=$1
fi

NAME=mypdcart-$VER
TMPDIR=dist/tmp/"${NAME}"

mkdir -p "${TMPDIR}/src/cartsio"
mkdir -p "${TMPDIR}/src/libflash"
mkdir -p "${TMPDIR}/src/mypdos"
mkdir -p "${TMPDIR}/src/hisio"

cp -a \
	atr2cart.exe \
	diskcart.atr \
	diskcart-atarimax8.atr diskcart-freezer.atr diskcart-mega512.atr \
	diskcart-atarimax8.com diskcart-freezer.com diskcart-mega512.com \
	ctesta8.com ctestme.com \
	"${TMPDIR}"

cp -a Makefile piconame*.txt *.inc *.src *.cpp *.c *.h "${TMPDIR}/src"
cp -a cartsio/*.src cartsio/*.inc "${TMPDIR}/src/cartsio"
cp -a libflash/*.src libflash/*.inc "${TMPDIR}/src/libflash"
cp -a mypdos/*.src mypdos/*.inc "${TMPDIR}/src/mypdos"
cp -a hisio/*.src hisio/*.inc "${TMPDIR}/src/hisio"

rm -f "dist/${NAME}".zip
cd dist/tmp
zip -r "../${NAME}.zip" ${NAME}
cd ..
rm -rf tmp
